### ISSUE TITLE
Improve static app

### ISSUE THREAD

**Issue by ianwremmel** [ianwremmel/displace#36]
- [ ] add product explanation
- [ ] use requestb.in as default
- [ ] add curl example #29 
- [ ] auto-expand text areas #27 
- [ ] make template/payload more interesting #26
