### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ianwremmel** [ianwremmel/displace#37]
- [ ] Improve static app #36 
- [ ] Explain motivation in README
- [ ] Document hosting options #23 
  - [ ] run as standalone node app (with static site)
  - [ ] deploy to AWS

**Comment by ianwremmel** [comment]
Possible README Content

```markdown
# Displace

> Zero configuration webhook middleware

With nothing but a URL, transform your outgoing webhooks before they reaching their final destination.

## What Is This?

Webhooks are great - they make it easy to integrate third-party services with your apps. But what happens when you want to integrate two third-party services that you don't control? With displace, you can forward one webhook to another while transforming it in the middle. Let's say you want to post messages from GitHub into a Slack channel. Rather than relying on the format that slack's GitHub integration provides, you can give github a displace link that includes a `template` and a `destination`. That `template` is a [mustache](https://mustache.github.io/) template and the `destination` is the Incoming Webhook URL.

Don't worry, the [app below](#app) will help you deal with all the URL encoding.

## Motivation

I've always been a bit let-down by the GUI services for doing sort of things. Where Yahoo Pipes was a bit too complicated, IFTTT, Zapier, and the often a feel a bit too simple; they never quite support what I want to do. More importantly though, this was an educational challenge: this service is an experiment into running code on Amazone Lambda. 

## Privacy

This is still an experiment in using Amazon Lambda. For now, expect that any data transiting this service may be logged. Future versions may support obfuscating URLs and payloads. If privacy is a concern, you're better off hopping over to github to run your own version.

## Roadmap

- User Signups
- Rate Limiting
- Billing
- Filtering
- Store and Forward
- Log Obfuscation
```
